# Copyright 2021  The RXV64 Authors
# All rights reserved
#
# Use of this source code is governed by an MIT-style
# license that can be found in the LICENSE file or at
# https://opensource.org/licenses/MIT.

[workspace]
resolver = "2"

members = [
    "kernel",
    "syslib",
    "ulib",
    "xtask",
]

[profile.dev]
panic = "abort"
opt-level = 1  # enables enough optimization for reasonable stack usage

[profile.release]
panic = "abort"
debug = true
